### ISSUE TITLE
Miniflux example

### ISSUE THREAD

**Issue by caseydierking** [containeroo/Traefik-examples#2]
Your traefik 2.0 configurations are a life saver. I was wondering if you would be interested in looking at creating one for miniflux? i've attempted it several times with no luck. Their docker instructions are at the bottom of the page. 
https://miniflux.app/docs/installation.html

**Comment by rxbn** [comment]
thanks for the suggestion - we will look into that :)

**Comment by caseydierking** [comment]
I ended up figuring it out on my end. Maybe I'll make a pull request eventually
